pipeline {
    agent any
    environment {
        CI = 'true'
        // These environment variables will be pulled from Jenkins job configuration
        EC2_IP = "${EC2_IP}"
        APP_DIR = "${APP_DIR}"
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }
        stage('Deploy') {
            steps {
                sshagent(['ec2-ssh-credentials']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ec2-user@${EC2_IP} 'cd ${APP_DIR} && git pull && npm install && pm2 restart all || pm2 start npm --name "simple-app" -- start'
                    """
                }
            }
        }
    }
}
